ALL_SKILLS = [
    "Astrogation (Int)",
    "Athletics (Br)",
    "Charm (Pr)",
    "Coercion (Will)",
    "Computers (Int)",
    "Cool (Pr)",
    "Coordination (Ag)",
    "Deception (Cun)",
    "Discipline (Will)",
    "Leadership (Pr)",
    "Mechanics (Int)",
    "Medicine (Int)",
    "Negotiation (Pr)",
    "Perception (Cun)",
    "Piloting - Planetary (Ag)",
    "Piloting - Space (Ag)",
    "Resilience (Br)",
    "Skulduggery (Cun)",
    "Stealth (Ag)",
    "Streetwise (Cun)",
    "Survival (Cun)",
    "Vigilance (Will)",
    "Knowledge - Core Worlds (Int)",
    "Knowledge - Education (Int)",
    "Knowledge - Lore (Int)",
    "Knowledge - Outer Rim (Int)",
    "Knowledge - Underworld (Int)",
    "Knowledge - Xenology (Int)",
    "Brawl (Br)",
    "Gunnery (Ag)",
    "Melee (Br)",
    "Ranged - Light (Ag)",
    "Ranged - Heavy (Ag)"
]