SPECIES_DATA = {
    "Human": {
        "brawn": 2,
        "agility": 2,
        "intellect": 2,
        "cunning": 2,
        "willpower": 2,
        "presence": 2,
    },
    "Twi'lek": {
        "brawn": 1,
        "agility": 2,
        "intellect": 2,
        "cunning": 2,
        "willpower": 2,
        "presence": 3,
    },
    "Trandoshan": {
        "brawn": 3,
        "agility": 1,
        "intellect": 2,
        "cunning": 2,
        "willpower": 2,
        "presence": 2,
    },
    "Wookiee": {
        "brawn": 3,
        "agility": 2,
        "intellect": 2,
        "cunning": 2,
        "willpower": 1,
        "presence": 2,
    },
    "Gand": {
        "brawn": 2,
        "agility": 2,
        "intellect": 2,
        "cunning": 2,
        "willpower": 3,
        "presence": 1,
    },
    "Rodian": {
        "brawn": 2,
        "agility": 3,
        "intellect": 2,
        "cunning": 2,
        "willpower": 1,
        "presence": 2,
    },
    "Devaronian": {
        "brawn": 2,
        "agility": 2,
        "intellect": 2,
        "cunning": 3,
        "willpower": 2,
        "presence": 1,
    },
    "Weequay": {
        "brawn": 3,
        "agility": 2,
        "intellect": 1,
        "cunning": 3,
        "willpower": 2,
        "presence": 1,
    }
}